export const FETCH_ARCADES = 'FETCH_ARCADES';
export const FETCH_ARCADE_BY_ID_SUCCESS = 'FETCH_ARCADE_BY_ID_SUCCESS'
export const FETCH_ARCADE_BY_ID_INIT = 'FETCH_ARCADE_BY_ID_INIT';
export const FETCH_ARCADES_SUCCESS = 'FETCH_ARCADES_SUCCESS';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';